"""Contains dictionaries mapping in game text strings to the GOOD format.

Edit this file when new characters and artifacts are added."""

setKey = {
    "Gladiator's Finale": "GladiatorsFinale",
    "Wanderer's Troupe": "WanderersTroupe",
    "Thundersoother": "Thundersoother",
    "Thundering Fury": "ThunderingFury",
    "Maiden Beloved": "MaidenBeloved",
    "Viridescent Venerer": "ViridescentVenerer",
    "Crimson Witch of Flames": "CrimsonWitchOfFlames",
    "Lavawalker": "Lavawalker",
    "Noblesse Oblige": "NoblesseOblige",
    "Bloodstained Chivalry": "BloodstainedChivalry",
    "Archaic Petra": "ArchaicPetra",
    "Blizzard Strayer": "BlizzardStrayer",
    "Heart of Depth": "HeartOfDepth",
    "Tenacity of the Millelith": "TenacityOfTheMillelith",
    "Pale Flame": "PaleFlame",
    "Emblem of Severed Fate": "EmblemOfSeveredFate",
    "Shimenawa's Reminiscence": "ShimenawasReminiscence",
    "Husk of Opulent Dreams": "HuskOfOpulentDreams",
    "Ocean-Hued Clam": "OceanHuedClam",
    "Echoes of an Offering": "EchoesOfAnOffering",
    "Vermillion Hereafter": "VermillionHereafter",
    "Retracing Bolide": "RetracingBolide",
    "Deepwood Memories": "DeepwoodMemories",
    "Gilded Dreams": "GildedDreams",
    "Flower of Paradise Lost": "FlowerOfParadiseLost",
    "Desert Pavilion Chronicle": "DesertPavilionChronicle",
    "Nymph's Dream": "NymphsDream",
    "Vourukasha's Glow": "VourukashasGlow",
    "Golden Troupe": "GoldenTroupe",
    "Marechaussee Hunter": "MarechausseeHunter",
}

slotKey = {
    "Flower of Life": "flower",
    "Plume of Death": "plume",
    "Sands of Eon": "sands",
    "Goblet of Eonothem": "goblet",
    "Circlet of Logos": "circlet",
}

statKey = {
    "HP": "hp",
    "ATK": "atk",
    "DEF": "def",
    "HP%": "hp_",
    "ATK%": "atk_",
    "DEF%": "def_",
    "Physical DMG Bonus%": "physical_dmg_",
    "Pyro DMG Bonus%": "pyro_dmg_",
    "Electro DMG Bonus%": "electro_dmg_",
    "Cryo DMG Bonus%": "cryo_dmg_",
    "Hydro DMG Bonus%": "hydro_dmg_",
    "Anemo DMG Bonus%": "anemo_dmg_",
    "Geo DMG Bonus%": "geo_dmg_",
    "Dendro DMG Bonus%": "dendro_dmg_",
    "Elemental Mastery": "eleMas",
    "Energy Recharge%": "enerRech_",
    "CRIT Rate%": "critRate_",
    "CRIT DMG%": "critDMG_",
    "Healing Bonus%": "heal_",
}

location = {
    "Albedo": "Albedo",
    "Alhaitham": "Alhaitham",
    "Aloy": "Aloy",
    "Amber": "Amber",
    "Arataki Itto": "AratakiItto",
    "Baizhu": "Baizhu",
    "Barbara": "Barbara",
    "Beidou": "Beidou",
    "Bennett": "Bennett",
    "Candace": "Candace",
    "Charlotte": "Charlotte",
    "Chongyun": "Chongyun",
    "Clorinde": "Clorinde",
    "Collei": "Collei",
    "Cyno": "Cyno",
    "Dehya": "Dehya",
    "Diluc": "Diluc",
    "Diona": "Diona",
    "Dori": "Dori",
    "Eula": "Eula",
    "Faruzan": "Faruzan",
    "Fischl": "Fischl",
    "Freminet": "Freminet",
    "Furina": "Furina",
    "Ganyu": "Ganyu",
    "Gorou": "Gorou",
    "Hu Tao": "HuTao",
    "Jean": "Jean",
    "Kaedehara Kazuha": "KaedeharaKazuha",
    "Kaeya": "Kaeya",
    "Kamisato Ayaka": "KamisatoAyaka",
    "Kamisato Ayato": "KamisatoAyato",
    "Kaveh": "Kaveh",
    "Keqing": "Keqing",
    "Kirara": "Kirara",
    "Klee": "Klee",
    "Kujou Sara": "KujouSara",
    "Kuki Shinobu": "KukiShinobu",
    "Layla": "Layla",
    "Lisa": "Lisa",
    "Lyney": "Lyney",
    "Lynette": "Lynette",
    "Mika": "Mika",
    "Mona": "Mona",
    "Nahida": "Nahida",
    "Navia": "Navia",
    "Neuvillette": "Neuvillette",
    "Nilou": "Nilou",
    "Ningguang": "Ningguang",
    "Noelle": "Noelle",
    "Qiqi": "Qiqi",
    "Raiden Shogun": "RaidenShogun",
    "Razor": "Razor",
    "Rosaria": "Rosaria",
    "Sangonomiya Kokomi": "SangonomiyaKokomi",
    "Sayu": "Sayu",
    "Shikanoin Heizou": "ShikanoinHeizou",
    "Shenhe": "Shenhe",
    "Sucrose": "Sucrose",
    "Tartaglia": "Tartaglia",
    "Tighnari": "Tighnari",
    "Thoma": "Thoma",
    "Autumnstar": "Traveler",
    "Venti": "Venti",
    "Wanderer": "Wanderer",
    "Wriothesley": "Wriothesley",
    "Xiangling": "Xiangling",
    "Xiao": "Xiao",
    "Xingqiu": "Xingqiu",
    "Xinyan": "Xinyan",
    "Yanfei": "Yanfei",
    "Yaoyao": "Yaoyao",
    "Yelan": "Yelan",
    "Yae Miko": "YaeMiko",
    "Yoimiya": "Yoimiya",
    "Yun Jin": "YunJin",
    "Zhongli": "Zhongli",
}
